services:
  bot:
    env_file:
      - .env.dev
    environment:
      DATABASE_URL: postgresql://bot_platform_finance:bot_platform_finance@postgres:5432/bot_platform_finance
    command: ["python", "-m", "uvicorn", "api.telegram_webhook:app", "--host", "0.0.0.0", "--port", "3000", "--reload"]
    volumes:
      - .:/app
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    extends:
      file: docker/postgres/docker-compose.yml
      service: postgres

  dozzle:
    extends:
      file: docker/dozzle/docker-compose.yml
      service: dozzle

volumes:
  postgres_dev_data:
